[package]
name = "ltr"

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
# workspace crates
phx.workspace = true

# external crates
build-time = "0.1"
clap = { version = "4.4", features = ["derive"] }
git-version = "0.3"
libc = "0.2"

[build-dependencies]
winres = "0.1"
